package org.bankapp.domain;
// Generated Apr 21, 2014 10:52:35 AM by Hibernate Tools 3.2.1.GA

/**
 * Bankuser generated by hbm2java
 */
public class Bankuser implements java.io.Serializable {

    private Long userId;
    private String password;
    private Byte[] secretKey;
    private String oldPassword;
    private String role;

    public Bankuser(Long userId, String password, Byte[] secretKey, String oldPassword, String role) {
        this.userId = userId;
        this.password = password;
        this.secretKey = secretKey;
        this.oldPassword = oldPassword;
        this.role = role;
    }

    public String getOldPassword() {
        return oldPassword;
    }

    public void setOldPassword(String oldPassword) {
        this.oldPassword = oldPassword;
    }

    public Bankuser() {
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Byte[] getSecretKey() {
        return secretKey;
    }

    public void setSecretKey(Byte[] secretKey) {
        this.secretKey = secretKey;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public Bankuser(Long userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        return "Bankuser{" + "userId=" + userId + ", password=" + password + ", secretKey=" + secretKey + ", role=" + role + '}';
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + (this.userId != null ? this.userId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Bankuser other = (Bankuser) obj;
        if (this.userId != other.userId && (this.userId == null || !this.userId.equals(other.userId))) {
            return false;
        }
        return true;
    }
}
