package org.bankapp.domain;
// Generated Apr 21, 2014 10:52:35 AM by Hibernate Tools 3.2.1.GA

/**
 * Balance generated by hbm2java
 */
public class Balance implements java.io.Serializable {

    private Long accountId;
    private Double balance;

    public Balance(Long accountId, Double balance) {
        this.accountId = accountId;
        this.balance = balance;
    }

    public Long getAccountId() {
        return accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    public Double getBalance() {
        return balance;
    }

    public void setBalance(Double balance) {
        this.balance = balance;
    }

    public Balance() {
    }

    @Override
    public String toString() {
        return "Balance{" + "accountId=" + accountId + ", balance=" + balance + '}';
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 41 * hash + (this.accountId != null ? this.accountId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Balance other = (Balance) obj;
        if (this.accountId != other.accountId && (this.accountId == null || !this.accountId.equals(other.accountId))) {
            return false;
        }
        return true;
    }
}
