package org.bankapp.domain;
// Generated Apr 21, 2014 10:52:35 AM by Hibernate Tools 3.2.1.GA



/**
 * Balance generated by hbm2java
 */
public class Balance  implements java.io.Serializable {


     private long accountId;
     private Double balance;

    public Balance() {
    }

	
    public Balance(long accountId) {
        this.accountId = accountId;
    }
    public Balance(long accountId, Double balance) {
       this.accountId = accountId;
       this.balance = balance;
    }
   
    public long getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(long accountId) {
        this.accountId = accountId;
    }
    public Double getBalance() {
        return this.balance;
    }
    
    public void setBalance(Double balance) {
        this.balance = balance;
    }




}


