package org.bankapp.domain;
// Generated Apr 21, 2014 10:52:35 AM by Hibernate Tools 3.2.1.GA



/**
 * Bankuser generated by hbm2java
 */
public class Bankuser  implements java.io.Serializable {


     private Long userId;
     private String password;
     private String secretKey;
     private String role;

    public Bankuser() {
    }

	
    public Bankuser(Long userId) {
        this.userId = userId;
    }
    public Bankuser(Long userId, String password, String secretKey, String role) {
       this.userId = userId;
       this.password = password;
       this.secretKey = secretKey;
       this.role = role;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getSecretKey() {
        return this.secretKey;
    }
    
    public void setSecretKey(String secretKey) {
        this.secretKey = secretKey;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


