package org.bankapp.domain;
// Generated Apr 21, 2014 10:52:35 AM by Hibernate Tools 3.2.1.GA



/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Long customerId;
     private Long accountId;
     private Long detaildId;
     private Long userId;

    public Customer() {
    }

	
    public Customer(Long customerId) {
        this.customerId = customerId;
    }
    public Customer(Long customerId, Long accountId, Long detaildId, Long userId) {
       this.customerId = customerId;
       this.accountId = accountId;
       this.detaildId = detaildId;
       this.userId = userId;
    }
   
    public long getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }
    public Long getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }
    public Long getDetaildId() {
        return this.detaildId;
    }
    
    public void setDetaildId(Long detaildId) {
        this.detaildId = detaildId;
    }
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }




}


