package org.bankapp.domain;
// Generated Apr 21, 2014 10:52:35 AM by Hibernate Tools 3.2.1.GA

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

    private Long customerId;
    private Balance accountId;
    private Details detaildId;
    private Bankuser userId;

    public Customer(Long customerId, Balance accountId, Details detaildId, Bankuser userId) {
        this.customerId = customerId;
        this.accountId = accountId;
        this.detaildId = detaildId;
        this.userId = userId;
    }

    public Customer(Long customerId) {
        this.customerId = customerId;
    }

    public Customer() {
    }

    public Long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public Balance getAccountId() {
        return accountId;
    }

    public void setAccountId(Balance accountId) {
        this.accountId = accountId;
    }

    public Details getDetaildId() {
        return detaildId;
    }

    public void setDetaildId(Details detaildId) {
        this.detaildId = detaildId;
    }

    public Bankuser getUserId() {
        return userId;
    }

    public void setUserId(Bankuser userId) {
        this.userId = userId;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + (this.customerId != null ? this.customerId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Customer other = (Customer) obj;
        if (this.customerId != other.customerId && (this.customerId == null || !this.customerId.equals(other.customerId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Customer{" + "customerId=" + customerId + ", accountId=" + accountId + ", detaildId=" + detaildId + ", userId=" + userId + '}';
    }
}
