package org.bankapp.domain;
// Generated Apr 21, 2014 10:52:35 AM by Hibernate Tools 3.2.1.GA

/**
 * Details generated by hbm2java
 */
public class Details implements java.io.Serializable {

    private Long detailsId;
    private String firstName;
    private String lastName;
    private String mobile;
    private String emailId;
    private byte[] picture;
    private byte[] signature;
    private String accountType;
    private Double minimumBalance;

    public Details() {
    }
    private Address addressId;
    private String parentName;
    private String designation;

    public Details(Long detailsId, String firstName, String lastName, String mobile, String emailId, byte[] picture, byte[] signature, String accountType, Double minimumBalance, Address addressId, String parentName, String designation) {
        this.detailsId = detailsId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.mobile = mobile;
        this.emailId = emailId;
        this.picture = picture;
        this.signature = signature;
        this.accountType = accountType;
        this.minimumBalance = minimumBalance;
        this.addressId = addressId;
        this.parentName = parentName;
        this.designation = designation;
    }

    public Details(Long detailsId) {
        this.detailsId = detailsId;
    }

    public Long getDetailsId() {
        return detailsId;
    }

    public void setDetailsId(Long detailsId) {
        this.detailsId = detailsId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getEmailId() {
        return emailId;
    }

    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    public byte[] getPicture() {
        return picture;
    }

    public void setPicture(byte[] picture) {
        this.picture = picture;
    }

    public byte[] getSignature() {
        return signature;
    }

    public void setSignature(byte[] signature) {
        this.signature = signature;
    }

    public String getAccountType() {
        return accountType;
    }

    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    public Double getMinimumBalance() {
        return minimumBalance;
    }

    public void setMinimumBalance(Double minimumBalance) {
        this.minimumBalance = minimumBalance;
    }

    public Address getAddressId() {
        return addressId;
    }

    public void setAddressId(Address addressId) {
        this.addressId = addressId;
    }

    public String getParentName() {
        return parentName;
    }

    public void setParentName(String parentName) {
        this.parentName = parentName;
    }

    public String getDesignation() {
        return designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 41 * hash + (this.detailsId != null ? this.detailsId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Details other = (Details) obj;
        if (this.detailsId != other.detailsId && (this.detailsId == null || !this.detailsId.equals(other.detailsId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Details{" + "detailsId=" + detailsId + ", firstName=" + firstName + ", lastName=" + lastName + ", mobile=" + mobile + ", emailId=" + emailId + ", picture=" + picture + ", signature=" + signature + ", accountType=" + accountType + ", minimumBalance=" + minimumBalance + ", addressId=" + addressId + ", parentName=" + parentName + ", designation=" + designation + '}';
    }
}
